name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name : apt packages
      run: |
        sudo apt update
        sudo apt install -y valgrind
    - name: memcheck
      run: make memcheck
